config/routes.rb
Rails.application.routes.draw do
  get 'articles', to: 'articles#index'
  get 'articles/new', to: 'articles#new'
  get 'articles/:id', to: 'articles#show', as: :article
  post 'articles', to: 'articles#create'
  get 'articles/:id/edit', to: 'articles#edit', as: :edit_article
  patch 'articles/:id', to: 'articles#update'
  delete 'articles/:id', to: 'articles#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    @article.save
    redirect_to article_path(@article)
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content)
  end

  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">

<%= form_for (@article) do |f| %>
<div class="form-group" style="margin-left:45px;">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="form-group" style="margin-left:45px">
  <%= f.label :content %>
  <%= f.text_field :content %>
</div>


<div class="form-group" style="margin-left:45px">
  <%= f.submit class: "btn btn-primary" %>
</div>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit <%= @article.title %></h1>

<%= render "form" %>

app/views/articles/index.html.erb
<div class="banner border-bottom">
  <p> Wikinimous </p>
  <p> <%= link_to "Add a new article", articles_new_path, :class => 'new_article'  %> </p>
</div>
<h1 > One Piece quotes</h1>
<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>

<ul style="list-style-type: none">
  <% @articles.each do |article| %>
    <li> <%= link_to article.title, article_path(article), :class => 'article_links'  %></li>
  <% end %>
</ul>

app/views/articles/new.html.erb
<h1 style="margin-left:45px; margin-bottom:20px">Create a new article</h1>

<%= render "form" %>

app/views/articles/show.html.erb
<div class="banner border-bottom">
  <p> Wikinimous </p>
  <p> <%= link_to "Add a new article", articles_new_path, :class => 'new_article'  %> </p>
</div>

<link href='http://fonts.googleapis.com/css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900italic,900' rel='stylesheet' type='text/css'>

<h1 style="margin:0px 0px 10px 45px" ><%= @article.title %></h1>
<h3 class="btn btn-primary" style="opacity:1"> <%= @article.content %></h3>

<div class ="redirect">
  <p><%= link_to "Back to list", articles_path, :class => 'article_links' %></p>
  <p><%= link_to "Edit article", edit_article_path(@article), :class => 'article_links' %></p>
  <p><%= link_to "Delete article", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, :class => 'article_links' %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWikinimous</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>